services:
  backend:
    build: ./backend
    container_name: backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db

  liquibase:
    image: liquibase/liquibase:4.26
    container_name: liquibase
    volumes:
      - ./sqlScripts:/changelog
    command: >
      --url=jdbc:postgresql://db:5432/mydatabase
      --username=postgres
      --password=postgres
      --searchPath=/changelog
      --changelog-file=changelogs/V1__initial_schema.sql
      update
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
