name: Pipeline

on:
  push:
    branches: [main, master]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/pipeline.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/pipeline.yml'
  workflow_dispatch:

jobs:
  check_paths:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  frontend:
    name: frontend-ci
    needs: check_paths
    if: needs.check_paths.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend-ci.yml

  backend:
    name: backend-ci
    needs: check_paths
    if: needs.check_paths.outputs.backend == 'true'
    uses: ./.github/workflows/backend-ci.yml
